export const F_BLOG_POST = {
  blog_post_url: {
    id: "blog_post_url",
    label: "Blog Post URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/",
  },
  title: {
    id: "title",
    label: "Title",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. Title",
  },
  content: {
    id: "content",
    label: "Content",
    is_required: true,
    max_length: 2047,
    placeholder: "ex. Content",
  },
  tags: {
    id: "tags",
    label: "Tags",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Tags",
    default_value: "[]",
  },
  og_title: {
    id: "og_title",
    label: "OG Title",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Title",
  },
  og_description: {
    id: "og_description",
    label: "OG Description",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Description",
  },
  og_image: {
    id: "og_image",
    label: "OG Image",
    is_required: false,
    max_length: 2048,
    placeholder: "ex. OG Image",
  },
  og_url: {
    id: "og_url",
    label: "OG URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG URL",
  },
  local_image_url: {
    id: "local_image_url",
    label: "Local Image URL",
    is_required: false,
    max_length: 2048,
    placeholder: "ex. Local Image URL",
  },
  platform: {
    id: "platform",
    label: "Platform",
    is_required: true,
    max_length: 100,
    placeholder: "ex. blog, facebook, twitter, etc.",
  },
  platform_url: {
    id: "platform_url",
    label: "Platform URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/",
  },
  published_date: {
    id: "published_date",
    label: "Published Date",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Published Date",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  metadata_json: {
    id: "metadata_json",
    label: "Metadata JSON",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. JSON",
    default_value: "[]",
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "true",
  },
  is_deleted: {
    id: "is_deleted",
    label: "Is Deleted",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  deleted_at: {
    id: "deleted_at",
    label: "Deleted At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
};
