export const F_BLOG_POST = {
  uuid_36: {
    id: "uuid_36",
    label: "UUID 36",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  blog_post_url: {
    id: "blog_post_url",
    label: "Blog Post URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/",
  },
  title: {
    id: "title",
    label: "Title",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. Title",
  },
  content: {
    id: "content",
    label: "Content",
    is_required: true,
    max_length: 2047,
    placeholder: "ex. Content",
  },
  tags: {
    id: "tags",
    label: "Tags",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Tags",
    default_value: "[]",
  },
  og_title: {
    id: "og_title",
    label: "OG Title",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Title",
  },
  og_description: {
    id: "og_description",
    label: "OG Description",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Description",
  },
  og_image: {
    id: "og_image",
    label: "OG Image",
    is_required: false,
    max_length: 2048,
    placeholder: "ex. OG Image",
  },
  og_url: {
    id: "og_url",
    label: "OG URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG URL",
  },
  local_image_url: {
    id: "local_image_url",
    label: "Local Image URL",
    is_required: false,
    max_length: 2048,
    placeholder: "ex. Local Image URL",
  },
  platform: {
    id: "platform",
    label: "Platform",
    is_required: true,
    max_length: 100,
    placeholder: "ex. blog, facebook, twitter, etc.",
  },
  platform_url: {
    id: "platform_url",
    label: "Platform URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/",
  },
  published_date: {
    id: "published_date",
    label: "Published Date",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Published Date",
  },
  info_country: {
    id: "info_country",
    label: "Info Country",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Country",
    default_value: "[]",
  },
  info_city: {
    id: "info_city",
    label: "Info City",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info City",
    default_value: "[]",
  },
  info_district: {
    id: "info_district",
    label: "Info District",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info District",
    default_value: "[]",
  },
  info_neighborhood: {
    id: "info_neighborhood",
    label: "Info Neighborhood",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Neighborhood",
    default_value: "[]",
  },
  info_landmark: {
    id: "info_landmark",
    label: "Info Landmark",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Landmark",
    default_value: "[]",
  },
  info_category: {
    id: "info_category",
    label: "Info Category",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Category",
    default_value: "[]",
  },
  info_name: {
    id: "info_name",
    label: "Info Name",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Name",
    default_value: "[]",
  },
  info_special_tag: {
    id: "info_special_tag",
    label: "Info Special Tag",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Special Tag",
    default_value: "[]",
  },
  info_influencer: {
    id: "info_influencer",
    label: "Info Influencer",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Influencer",
    default_value: "[]",
  },
  info_season: {
    id: "info_season",
    label: "Info Season",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Season",
    default_value: "[]",
  },
  info_time_of_day: {
    id: "info_time_of_day",
    label: "Info Time of Day",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Time of Day",
    default_value: "[]",
  },
  info_activity_type: {
    id: "info_activity_type",
    label: "Info Activity Type",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Activity Type",
    default_value: "[]",
  },
  info_reservation_required: {
    id: "info_reservation_required",
    label: "Info Reservation Required",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  info_travel_tips: {
    id: "info_travel_tips",
    label: "Info Travel Tips",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Info Travel Tips",
    default_value: "[]",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  metadata_json: {
    id: "metadata_json",
    label: "Metadata JSON",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. JSON",
    default_value: "[]",
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "true",
  },
  is_deleted: {
    id: "is_deleted",
    label: "Is Deleted",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  deleted_at: {
    id: "deleted_at",
    label: "Deleted At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
};
