export const F_BLOG_POST = {
  id: {
    id: "id",
    label: "ID",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  blog_post_url: {
    id: "blog_post_url",
    label: "Blog Post URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/",
  },
  featured_image_url: {
    id: "featured_image_url",
    label: "Featured Image URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/featured_image.jpg",
  },
  title: {
    id: "title",
    label: "Title",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. Title",
  },
  content: {
    id: "content",
    label: "Content",
    is_required: true,
    max_length: 2047,
    placeholder: "ex. Content",
  },
  tags: {
    id: "tags",
    label: "Tags",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Tags",
    default_value: "[]",
  },
  platform: {
    id: "platform",
    label: "Platform",
    is_required: true,
    max_length: 100,
    placeholder: "ex. blog, facebook, twitter, etc.",
  },
  platform_url: {
    id: "platform_url",
    label: "Platform URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.blog.com/1234567890/",
  },
  published_date: {
    id: "published_date",
    label: "Published Date",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Published Date",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  metadata_json: {
    id: "metadata_json",
    label: "Metadata JSON",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. JSON",
    default_value: "[]",
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "true",
  },
  is_deleted: {
    id: "is_deleted",
    label: "Is Deleted",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  deleted_at: {
    id: "deleted_at",
    label: "Deleted At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
};
