export const F_INSTAGRAM_POST = {
  instagram_post_url: {
    id: "instagram_post_url",
    label: "Instagram Post URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.instagram.com/p/1234567890/",
  },
  post_type: {
    id: "post_type",
    label: "Post Type",
    is_required: true,
    max_length: 20,
    placeholder: "ex. post, story, reel, IGTV, etc.",
  },
  media_count: {
    id: "media_count",
    label: "Media Count",
    is_required: true,
    max_length: 50,
    placeholder: "ex. 1, 2, 3, ...",
    default_value: 1,
  },
  media_urls: {
    id: "media_urls",
    label: "Media URLs",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.instagram.com/p/1234567890/media_1.jpg, https://www.instagram.com/p/1234567890/media_2.jpg, etc.",
    default_value: "[]",
  },
  og_title: {
    id: "og_title",
    label: "OG Title",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Title",
  },
  og_description: {
    id: "og_description",
    label: "OG Description",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Description",
  },
  og_image: {
    id: "og_image",
    label: "OG Image",
    is_required: false,
    max_length: 2048,
    placeholder: "ex. OG Image",
  },
  og_url: {
    id: "og_url",
    label: "OG URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG URL",
  },
  og_ios_url: {
    id: "og_ios_url",
    label: "OG iOS URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG iOS URL",
  },
  og_android_package: {
    id: "og_android_package",
    label: "OG Android Package",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Android Package",
  },
  og_android_url: {
    id: "og_android_url",
    label: "OG Android URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Android URL",
  },
  like_count: {
    id: "like_count",
    label: "Like Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  comment_count: {
    id: "comment_count",
    label: "Comment Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  view_count: {
    id: "view_count",
    label: "View Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  description: {
    id: "description",
    label: "Description",
    is_required: false,
    max_length: 2047,
    placeholder: "ex. Description",
  },
  tags: {
    id: "tags",
    label: "Tags",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Tags",
    default_value: "[]",
  },
  user_id: {
    id: "user_id",
    label: "User ID",
    is_required: false,
    max_length: 50,
    placeholder: "ex. User ID",
  },
  user_name: {
    id: "user_name",
    label: "User Name",
    is_required: false,
    max_length: 255,
    placeholder: "ex. User Name",
  },
  user_profile_url: {
    id: "user_profile_url",
    label: "User Profile URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. User Profile URL",
  },
  published_date: {
    id: "published_date",
    label: "Published Date",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Published Date",
  },
  local_image_url: {
    id: "local_image_url",
    label: "Local Image URL",
    is_required: false,
    max_length: 511,
    placeholder: "ex. Local Image URL",
  },
  location_name: {
    id: "location_name",
    label: "Location Name",
    is_required: false,
    max_length: 255,
    placeholder: "ex. Location Name",
  },
  location_id: {
    id: "location_id",
    label: "Location ID",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Location ID",
  },
  latitude: {
    id: "latitude",
    label: "Latitude",
    is_required: false,
    max_length: 20,
    placeholder: "ex. Latitude",
  },
  longitude: {
    id: "longitude",
    label: "Longitude",
    is_required: false,
    max_length: 20,
    placeholder: "ex. Longitude",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  metadata_json: {
    id: "metadata_json",
    label: "Metadata JSON",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. JSON",
    default_value: "[]",
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "true",
  },
  is_deleted: {
    id: "is_deleted",
    label: "Is Deleted",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  deleted_at: {
    id: "deleted_at",
    label: "Deleted At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
};
