export const F_QNA_LOG = {
  id: {
    id: "id",
    label: "QNA Log ID",
    is_required: true,
    max_length: 36,
    placeholder: "ex. UUID",
  },
  question_lang: {
    id: "question_lang",
    label: "Question Lang",
    is_required: true,
    max_length: 10,
    placeholder: "ex. en, ko, etc.",
  },
  question_native: {
    id: "question_native",
    label: "Question Native",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Question Native",
  },
  question_en: {
    id: "question_en",
    label: "Answer Native",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Answer Native",
  },
  answer_en: {
    id: "answer_en",
    label: "Answer EN",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. Answer EN",
  },
  answer_native: {
    id: "answer_native",
    label: "Answer Native",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Answer Native",
  },
  user_feedback: {
    id: "user_feedback",
    label: "User Feedback",
    is_required: false,
    max_length: 20,
    placeholder: "ex. User Feedback",
  },
  user_rating: {
    id: "user_rating",
    label: "User Rating",
    is_required: false,
    max_length: 10,
    placeholder: "ex. 0.9",
  },
  user_comment: {
    id: "user_comment",
    label: "User Comment",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. User Comment",
  },
  ai_model: {
    id: "ai_model",
    label: "AI Model",
    is_required: false,
    max_length: 50,
    placeholder: "ex. gpt-4o",
  },
  ai_confidence: {
    id: "ai_confidence",
    label: "AI Confidence",
    is_required: false,
    max_length: 10,
    placeholder: "ex. 0.9",
  },
  response_time_ms: {
    id: "response_time_ms",
    label: "Response Time MS",
    is_required: false,
    max_length: 10,
    placeholder: "ex. 100",
  },
  token_count: {
    id: "token_count",
    label: "Token Count",
    is_required: false,
    max_length: 10,
    placeholder: "ex. 100",
  },
  user_id: {
    id: "user_id",
    label: "User ID",
    is_required: false,
    max_length: 255,
    placeholder: "ex. user_id",
  },
  session_id: {
    id: "session_id",
    label: "Session ID",
    is_required: false,
    max_length: 255,
    placeholder: "ex. session_id",
  },
  ip_hash: {
    id: "ip_hash",
    label: "IP Hash",
    is_required: false,
    max_length: 64,
    placeholder: "ex. ip_hash",
  },
  context_type: {
    id: "context_type",
    label: "Context Type",
    is_required: false,
    max_length: 50,
    placeholder: "ex. question, answer, etc.",
  },
  context_id: {
    id: "context_id",
    label: "Context ID",
    is_required: false,
    max_length: 255,
    placeholder: "ex. context_id",
  },
  referenced_sources: {
    id: "referenced_sources",
    label: "Referenced Sources",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. referenced_sources",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 12,
    placeholder: "ex. 2025-01-01",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 12,
    placeholder: "ex. 2025-01-01",
  },
  is_helpful: {
    id: "is_helpful",
    label: "Is Helpful",
    is_required: false,
    placeholder: "ex. false",
  },
  is_flagged: {
    id: "is_flagged",
    label: "Is Flagged",
    is_required: true,
    default_value: false,
  },
  flagged_reason: {
    id: "flagged_reason",
    label: "Flagged Reason",
    is_required: false,
    max_length: 255,
    placeholder: "ex. flagged_reason",
  },
  is_reviewed: {
    id: "is_reviewed",
    label: "Is Reviewed",
    is_required: true,
    default_value: false,
  },
  reviewed_at: {
    id: "reviewed_at",
    label: "Reviewed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  reviewed_by: {
    id: "reviewed_by",
    label: "Reviewed By",
    is_required: false,
    max_length: 511,
    placeholder: "ex. reviewed_by",
  },
};
