export const F_TEXT = {
  id: {
    id: "id",
    label: "ID",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  hash_key: {
    id: "hash_key",
    label: "Hash Key",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  title: {
    id: "title",
    label: "Title",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. Title",
  },
  content: {
    id: "content",
    label: "Content",
    is_required: true,
    max_length: 2047,
    placeholder: "ex. Content",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  metadata_json: {
    id: "metadata_json",
    label: "Metadata JSON",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. JSON",
    default_value: "[]",
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "true",
  },
  is_deleted: {
    id: "is_deleted",
    label: "Is Deleted",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  deleted_at: {
    id: "deleted_at",
    label: "Deleted At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
};
