export const F_YOUTUBE_VIDEO_PROCESSING_LOG = {
  id: {
    id: "id",
    label: "ID",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  video_id: {
    id: "video_id",
    label: "Video ID",
    is_required: true,
    max_length: 20,
    placeholder: "ex. video_123",
  },
  processing_status: {
    id: "name",
    label: "Processing Status",
    is_required: true,
    max_length: 20,
    placeholder: "ex. pending, processing, completed, failed",
    default_value: "pending",
  },
  error_message: {
    id: "error_message",
    label: "Error Message",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Error message",
  },
  index_name: {
    id: "index_name",
    label: "Pinecone Index Name",
    is_required: true,
    max_length: 100,
    placeholder: "PK ex. food_restaurants_index",
  },
  is_api_data_fetched: {
    id: "is_api_data_fetched",
    label: "Is API Data Fetched",
    is_required: true,
    placeholder: "ex. false",
    default_value: false,
  },
  is_transcript_fetched: {
    id: "is_transcript_fetched",
    label: "Is Transcript Fetched",
    is_required: true,
    placeholder: "ex. false",
    default_value: false,
  },
  is_pinecone_processed: {
    id: "is_pinecone_processed",
    label: "Is Pinecone Processed",
    is_required: true,
    placeholder: "ex. false",
    default_value: false,
  },
  processing_started: {
    id: "processing_started",
    label: "Processing Started",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  processing_completed: {
    id: "processing_completed",
    label: "Processing Completed",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Default value is now",
  },
};
