export const F_YOUTUBE_VIDEO_TRANSCRIPT = {
  id: {
    id: "id",
    label: "ID",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  video_id: {
    id: "video_id",
    label: "Video ID",
    is_required: true,
    max_length: 20,
    placeholder: "ex. video_123",
  },
  language: {
    id: "language",
    label: "Language",
    is_required: true,
    max_length: 10,
    placeholder: "ex. en, ko, etc.",
    default_value: "ko",
  },
  total_duration: {
    id: "total_duration",
    label: "Total Duration",
    is_required: false,
    max_length: 10,
    placeholder: "ex. NUMERIC(12, 2)",
    default_value: 0,
  },
  segment_count: {
    id: "segment_count",
    label: "Segment Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  segments_storage_path: {
    id: "segments_storage_path",
    label: "Segments Storage Path",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. Storage Path",
    default_value: null,
  },
  segments_file_size: {
    id: "segments_file_size",
    label: "Segments File Size",
    is_required: false,
    max_length: 10,
    placeholder: "ex. BIGINT",
    default_value: null,
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
};
