export const ALL_LANGUAGES = [
  { lang_code: "xx", lang_name: "NONE", native_name: "NONE" },
  { lang_code: "ab", lang_name: "Abkhazian", native_name: "Abkhazian" },
  { lang_code: "aa", lang_name: "Afar", native_name: "Afar" },
  { lang_code: "af", lang_name: "Afrikaans", native_name: "Afrikaans" },
  { lang_code: "ak", lang_name: "Akan", native_name: "Akan" },
  { lang_code: "sq", lang_name: "Albanian", native_name: "Albanian" },
  { lang_code: "am", lang_name: "Amharic", native_name: "Amharic" },
  { lang_code: "ar", lang_name: "Arabic", native_name: "Arabic" },
  { lang_code: "an", lang_name: "Aragonese", native_name: "Aragonese" },
  { lang_code: "hy", lang_name: "Armenian", native_name: "Armenian" },
  { lang_code: "as", lang_name: "Assamese", native_name: "Assamese" },
  { lang_code: "av", lang_name: "Avaric", native_name: "Avaric" },
  { lang_code: "ae", lang_name: "Avestan", native_name: "Avestan" },
  { lang_code: "ay", lang_name: "Aymara", native_name: "Aymara" },
  { lang_code: "az", lang_name: "Azerbaijani", native_name: "Azerbaijani" },
  { lang_code: "bm", lang_name: "Bambara", native_name: "Bambara" },
  { lang_code: "ba", lang_name: "Bashkir", native_name: "Bashkir" },
  { lang_code: "eu", lang_name: "Basque", native_name: "Basque" },
  { lang_code: "be", lang_name: "Belarusian", native_name: "Belarusian" },
  { lang_code: "bn", lang_name: "Bengali (Bangla)", native_name: "Bengali (Bangla)" },
  { lang_code: "bh", lang_name: "Bihari", native_name: "Bihari" },
  { lang_code: "bi", lang_name: "Bislama", native_name: "Bislama" },
  { lang_code: "bs", lang_name: "Bosnian", native_name: "Bosnian" },
  { lang_code: "br", lang_name: "Breton", native_name: "Breton" },
  { lang_code: "bg", lang_name: "Bulgarian", native_name: "Bulgarian" },
  { lang_code: "my", lang_name: "Burmese", native_name: "Burmese" },
  { lang_code: "ca", lang_name: "Catalan", native_name: "Catalan" },
  { lang_code: "ch", lang_name: "Chamorro", native_name: "Chamorro" },
  { lang_code: "ce", lang_name: "Chechen", native_name: "Chechen" },
  { lang_code: "ny", lang_name: "Chichewa, Chewa, Nyanja", native_name: "Chichewa, Chewa, Nyanja" },
  { lang_code: "zh-hans", lang_name: "Chinese (Simplified)", native_name: "简体中文" },
  { lang_code: "zh-hant", lang_name: "Chinese (Traditional)", native_name: "繁體中文" },
  { lang_code: "cv", lang_name: "Chuvash", native_name: "Chuvash" },
  { lang_code: "kw", lang_name: "Cornish", native_name: "Cornish" },
  { lang_code: "co", lang_name: "Corsican", native_name: "Corsican" },
  { lang_code: "cr", lang_name: "Cree", native_name: "Cree" },
  { lang_code: "hr", lang_name: "Croatian", native_name: "Croatian" },
  { lang_code: "cs", lang_name: "Czech", native_name: "Czech" },
  { lang_code: "da", lang_name: "Danish", native_name: "Danish" },
  { lang_code: "dv", lang_name: "Divehi, Dhivehi, Maldivian", native_name: "Divehi, Dhivehi, Maldivian" },
  { lang_code: "nl", lang_name: "Dutch", native_name: "Dutch" },
  { lang_code: "dz", lang_name: "Dzongkha", native_name: "Dzongkha" },
  { lang_code: "en", lang_name: "English", native_name: "English" },
  { lang_code: "eo", lang_name: "Esperanto", native_name: "Esperanto" },
  { lang_code: "et", lang_name: "Estonian", native_name: "Estonian" },
  { lang_code: "ee", lang_name: "Ewe", native_name: "Ewe" },
  { lang_code: "fo", lang_name: "Faroese", native_name: "Faroese" },
  { lang_code: "fj", lang_name: "Fijian", native_name: "Fijian" },
  { lang_code: "fi", lang_name: "Finnish", native_name: "Finnish" },
  { lang_code: "fr", lang_name: "French", native_name: "Français" },
  { lang_code: "ff", lang_name: "Fula, Fulah, Pulaar, Pular", native_name: "Fula, Fulah, Pulaar, Pular" },
  { lang_code: "gl", lang_name: "Galician", native_name: "Galician" },
  { lang_code: "gd", lang_name: "Gaelic (Scottish)", native_name: "Gaelic (Scottish)" },
  { lang_code: "gv", lang_name: "Gaelic (Manx)", native_name: "Gaelic (Manx)" },
  { lang_code: "ka", lang_name: "Georgian", native_name: "Georgian" },
  { lang_code: "de", lang_name: "German", native_name: "Deutsch" },
  { lang_code: "el", lang_name: "Greek", native_name: "Greek" },
  { lang_code: "kl", lang_name: "Greenlandic", native_name: "Greenlandic" },
  { lang_code: "gn", lang_name: "Guarani", native_name: "Guarani" },
  { lang_code: "gu", lang_name: "Gujarati", native_name: "Gujarati" },
  { lang_code: "ht", lang_name: "Haitian Creole", native_name: "Haitian Creole" },
  { lang_code: "ha", lang_name: "Hausa", native_name: "Hausa" },
  { lang_code: "he", lang_name: "Hebrew", native_name: "Hebrew" },
  { lang_code: "hz", lang_name: "Herero", native_name: "Herero" },
  { lang_code: "hi", lang_name: "Hindi", native_name: "Hindi" },
  { lang_code: "ho", lang_name: "Hiri Motu", native_name: "Hiri Motu" },
  { lang_code: "hu", lang_name: "Hungarian", native_name: "Hungarian" },
  { lang_code: "is", lang_name: "Icelandic", native_name: "Icelandic" },
  { lang_code: "io", lang_name: "Ido", native_name: "Ido" },
  { lang_code: "ig", lang_name: "Igbo", native_name: "Igbo" },
  { lang_code: "id", lang_name: "Indonesian", native_name: "Bahasa Indonesia" },
  { lang_code: "in", lang_name: "Indonesian", native_name: "Bahasa Indonesia" },
  { lang_code: "ia", lang_name: "Interlingua", native_name: "Interlingua" },
  { lang_code: "ie", lang_name: "Interlingue", native_name: "Interlingue" },
  { lang_code: "iu", lang_name: "Inuktitut", native_name: "Inuktitut" },
  { lang_code: "ik", lang_name: "Inupiak", native_name: "Inupiak" },
  { lang_code: "ga", lang_name: "Irish", native_name: "Irish" },
  { lang_code: "it", lang_name: "Italian", native_name: "Italiano" },
  { lang_code: "ja", lang_name: "Japanese", native_name: "日本語" },
  { lang_code: "jv", lang_name: "Javanese", native_name: "Javanese" },
  { lang_code: "kn", lang_name: "Kannada", native_name: "Kannada" },
  { lang_code: "kr", lang_name: "Kanuri", native_name: "Kanuri" },
  { lang_code: "ks", lang_name: "Kashmiri", native_name: "Kashmiri" },
  { lang_code: "kk", lang_name: "Kazakh", native_name: "Kazakh" },
  { lang_code: "km", lang_name: "Khmer", native_name: "Khmer" },
  { lang_code: "ki", lang_name: "Kikuyu", native_name: "Kikuyu" },
  { lang_code: "rw", lang_name: "Kinyarwanda (Rwanda)", native_name: "Kinyarwanda (Rwanda)" },
  { lang_code: "rn", lang_name: "Kirundi", native_name: "Kirundi" },
  { lang_code: "ky", lang_name: "Kyrgyz", native_name: "Kyrgyz" },
  { lang_code: "kv", lang_name: "Komi", native_name: "Komi" },
  { lang_code: "kg", lang_name: "Kongo", native_name: "Kongo" },
  { lang_code: "ko", lang_name: "Korean", native_name: "한국어" },
  { lang_code: "ku", lang_name: "Kurdish", native_name: "Kurdish" },
  { lang_code: "kj", lang_name: "Kwanyama", native_name: "Kwanyama" },
  { lang_code: "lo", lang_name: "Lao", native_name: "Lao" },
  { lang_code: "la", lang_name: "Latin", native_name: "Latin" },
  { lang_code: "lv", lang_name: "Latvian (Lettish)", native_name: "Latvian (Lettish)" },
  { lang_code: "li", lang_name: "Limburgish (Limburger)", native_name: "Limburgish (Limburger)" },
  { lang_code: "ln", lang_name: "Lingala", native_name: "Lingala" },
  { lang_code: "lt", lang_name: "Lithuanian", native_name: "Lithuanian" },
  { lang_code: "lu", lang_name: "Luga-Katanga", native_name: "Luga-Katanga" },
  { lang_code: "lg", lang_name: "Luganda, Ganda", native_name: "Luganda, Ganda" },
  { lang_code: "lb", lang_name: "Luxembourgish", native_name: "Luxembourgish" },
  { lang_code: "mk", lang_name: "Macedonian", native_name: "Macedonian" },
  { lang_code: "mg", lang_name: "Malagasy", native_name: "Malagasy" },
  { lang_code: "ms", lang_name: "Malay", native_name: "Malay" },
  { lang_code: "ml", lang_name: "Malayalam", native_name: "Malayalam" },
  { lang_code: "mt", lang_name: "Maltese", native_name: "Maltese" },
  { lang_code: "mi", lang_name: "Maori", native_name: "Maori" },
  { lang_code: "mr", lang_name: "Marathi", native_name: "Marathi" },
  { lang_code: "mh", lang_name: "Marshallese", native_name: "Marshallese" },
  { lang_code: "mo", lang_name: "Moldavian", native_name: "Moldavian" },
  { lang_code: "mn", lang_name: "Mongolian", native_name: "Mongolian" },
  { lang_code: "na", lang_name: "Nauru", native_name: "Nauru" },
  { lang_code: "nv", lang_name: "Navajo", native_name: "Navajo" },
  { lang_code: "ng", lang_name: "Ndonga", native_name: "Ndonga" },
  { lang_code: "nd", lang_name: "Northern Ndebele", native_name: "Northern Ndebele" },
  { lang_code: "ne", lang_name: "Nepali", native_name: "Nepali" },
  { lang_code: "no", lang_name: "Norwegian", native_name: "Norwegian" },
  { lang_code: "nb", lang_name: "Norwegian bokmål", native_name: "Norwegian bokmål" },
  { lang_code: "nn", lang_name: "Norwegian Nynorsk", native_name: "Norwegian Nynorsk" },
  { lang_code: "ii", lang_name: "Nuosu, Sichuan Yi", native_name: "Sichuan Yi, Nuosu" },
  { lang_code: "oc", lang_name: "Occitan", native_name: "Occitan" },
  { lang_code: "oj", lang_name: "Ojibwe", native_name: "Ojibwe" },
  { lang_code: "cu", lang_name: "Old Church Slavonic, Old Bulgarian", native_name: "Old Church Slavonic, Old Bulgarian" },
  { lang_code: "or", lang_name: "Oriya", native_name: "Oriya" },
  { lang_code: "om", lang_name: "Oromo (Afaan Oromo)", native_name: "Oromo (Afaan Oromo)" },
  { lang_code: "os", lang_name: "Ossetian", native_name: "Ossetian" },
  { lang_code: "pi", lang_name: "Pāli", native_name: "Pāli" },
  { lang_code: "ps", lang_name: "Pashto, Pushto", native_name: "Pashto, Pushto" },
  { lang_code: "fa", lang_name: "Persian (Farsi)", native_name: "Persian (Farsi)" },
  { lang_code: "pl", lang_name: "Polish", native_name: "Polish" },
  { lang_code: "pt", lang_name: "Portuguese", native_name: "Portuguese" },
  { lang_code: "pa", lang_name: "Punjabi (Eastern)", native_name: "Punjabi (Eastern)" },
  { lang_code: "qu", lang_name: "Quechua", native_name: "Quechua" },
  { lang_code: "rm", lang_name: "Romansh", native_name: "Romansh" },
  { lang_code: "ro", lang_name: "Romanian", native_name: "Romanian" },
  { lang_code: "ru", lang_name: "Russian", native_name: "Russian" },
  { lang_code: "se", lang_name: "Sami", native_name: "Sami" },
  { lang_code: "sm", lang_name: "Samoan", native_name: "Samoan" },
  { lang_code: "sg", lang_name: "Sango", native_name: "Sango" },
  { lang_code: "sa", lang_name: "Sanskrit", native_name: "Sanskrit" },
  { lang_code: "sr", lang_name: "Serbian", native_name: "Serbian" },
  { lang_code: "sh", lang_name: "Serbo-Croatian", native_name: "Serbo-Croatian" },
  { lang_code: "st", lang_name: "Sesotho", native_name: "Sesotho" },
  { lang_code: "tn", lang_name: "Setswana", native_name: "Setswana" },
  { lang_code: "sn", lang_name: "Shona", native_name: "Shona" },
  { lang_code: "sd", lang_name: "Sindhi", native_name: "Sindhi" },
  { lang_code: "si", lang_name: "Sinhalese", native_name: "Sinhalese" },
  { lang_code: "ss", lang_name: "Siswati, Swati", native_name: "Siswati, Swati" },
  { lang_code: "sk", lang_name: "Slovak", native_name: "Slovak" },
  { lang_code: "sl", lang_name: "Slovenian", native_name: "Slovenian" },
  { lang_code: "so", lang_name: "Somali", native_name: "Somali" },
  { lang_code: "nr", lang_name: "Southern Ndebele", native_name: "Southern Ndebele" },
  { lang_code: "es", lang_name: "Spanish", native_name: "Español" },
  { lang_code: "su", lang_name: "Sundanese", native_name: "Sundanese" },
  { lang_code: "sw", lang_name: "Swahili (Kiswahili)", native_name: "Swahili (Kiswahili)" },
  { lang_code: "sv", lang_name: "Swedish", native_name: "Swedish" },
  { lang_code: "tl", lang_name: "Tagalog", native_name: "Tagalog" },
  { lang_code: "ty", lang_name: "Tahitian", native_name: "Tahitian" },
  { lang_code: "tg", lang_name: "Tajik", native_name: "Tajik" },
  { lang_code: "ta", lang_name: "Tamil", native_name: "Tamil" },
  { lang_code: "tt", lang_name: "Tatar", native_name: "Tatar" },
  { lang_code: "te", lang_name: "Telugu", native_name: "Telugu" },
  { lang_code: "th", lang_name: "Thai", native_name: "ไทย" },
  { lang_code: "bo", lang_name: "Tibetan", native_name: "Tibetan" },
  { lang_code: "ti", lang_name: "Tigrinya", native_name: "Tigrinya" },
  { lang_code: "to", lang_name: "Tonga", native_name: "Tonga" },
  { lang_code: "ts", lang_name: "Tsonga", native_name: "Tsonga" },
  { lang_code: "tr", lang_name: "Turkish", native_name: "Turkish" },
  { lang_code: "tk", lang_name: "Turkmen", native_name: "Turkmen" },
  { lang_code: "tw", lang_name: "Twi", native_name: "Twi" },
  { lang_code: "ug", lang_name: "Uyghur", native_name: "Uyghur" },
  { lang_code: "uk", lang_name: "Ukrainian", native_name: "Ukrainian" },
  { lang_code: "ur", lang_name: "Urdu", native_name: "Urdu" },
  { lang_code: "uz", lang_name: "Uzbek", native_name: "Uzbek" },
  { lang_code: "ve", lang_name: "Venda", native_name: "Venda" },
  { lang_code: "vi", lang_name: "Vietnamese", native_name: "Tiếng Việt" },
  { lang_code: "vo", lang_name: "Volapük", native_name: "Volapük" },
  { lang_code: "wa", lang_name: "Walloon", native_name: "Wallon" },
  { lang_code: "cy", lang_name: "Welsh", native_name: "Welsh" },
  { lang_code: "wo", lang_name: "Wolof", native_name: "Wolof" },
  { lang_code: "fy", lang_name: "Western Frisian", native_name: "Western Frisian" },
  { lang_code: "xh", lang_name: "Xhosa", native_name: "Xhosa" },
  { lang_code: "yi", lang_name: "Yiddish", native_name: "Yiddish" },
  { lang_code: "ji", lang_name: "Yiddish", native_name: "Yiddish" },
  { lang_code: "yo", lang_name: "Yoruba", native_name: "Yoruba" },
  { lang_code: "za", lang_name: "Zhuang, Chuang", native_name: "Zhuang, Chuang" },
  { lang_code: "zu", lang_name: "Zulu", native_name: "Zulu" },
];