export const ALL_LANGUAGES = [
  { lang_code: "xx", lang_name: "NONE", native: "NONE" },
  { lang_code: "ab", lang_name: "Abkhazian", native: "Abkhazian" },
  { lang_code: "aa", lang_name: "Afar", native: "Afar" },
  { lang_code: "af", lang_name: "Afrikaans", native: "Afrikaans" },
  { lang_code: "ak", lang_name: "Akan", native: "Akan" },
  { lang_code: "sq", lang_name: "Albanian", native: "Albanian" },
  { lang_code: "am", lang_name: "Amharic", native: "Amharic" },
  { lang_code: "ar", lang_name: "Arabic", native: "Arabic" },
  { lang_code: "an", lang_name: "Aragonese", native: "Aragonese" },
  { lang_code: "hy", lang_name: "Armenian", native: "Armenian" },
  { lang_code: "as", lang_name: "Assamese", native: "Assamese" },
  { lang_code: "av", lang_name: "Avaric", native: "Avaric" },
  { lang_code: "ae", lang_name: "Avestan", native: "Avestan" },
  { lang_code: "ay", lang_name: "Aymara", native: "Aymara" },
  { lang_code: "az", lang_name: "Azerbaijani", native: "Azerbaijani" },
  { lang_code: "bm", lang_name: "Bambara", native: "Bambara" },
  { lang_code: "ba", lang_name: "Bashkir", native: "Bashkir" },
  { lang_code: "eu", lang_name: "Basque", native: "Basque" },
  { lang_code: "be", lang_name: "Belarusian", native: "Belarusian" },
  { lang_code: "bn", lang_name: "Bengali (Bangla)", native: "Bengali (Bangla)" },
  { lang_code: "bh", lang_name: "Bihari", native: "Bihari" },
  { lang_code: "bi", lang_name: "Bislama", native: "Bislama" },
  { lang_code: "bs", lang_name: "Bosnian", native: "Bosnian" },
  { lang_code: "br", lang_name: "Breton", native: "Breton" },
  { lang_code: "bg", lang_name: "Bulgarian", native: "Bulgarian" },
  { lang_code: "my", lang_name: "Burmese", native: "Burmese" },
  { lang_code: "ca", lang_name: "Catalan", native: "Catalan" },
  { lang_code: "ch", lang_name: "Chamorro", native: "Chamorro" },
  { lang_code: "ce", lang_name: "Chechen", native: "Chechen" },
  { lang_code: "ny", lang_name: "Chichewa, Chewa, Nyanja", native: "Chichewa, Chewa, Nyanja" },
  { lang_code: "zh", lang_name: "Chinese", native: "Chinese" },
  { lang_code: "cv", lang_name: "Chuvash", native: "Chuvash" },
  { lang_code: "kw", lang_name: "Cornish", native: "Cornish" },
  { lang_code: "co", lang_name: "Corsican", native: "Corsican" },
  { lang_code: "cr", lang_name: "Cree", native: "Cree" },
  { lang_code: "hr", lang_name: "Croatian", native: "Croatian" },
  { lang_code: "cs", lang_name: "Czech", native: "Czech" },
  { lang_code: "da", lang_name: "Danish", native: "Danish" },
  { lang_code: "dv", lang_name: "Divehi, Dhivehi, Maldivian", native: "Divehi, Dhivehi, Maldivian" },
  { lang_code: "nl", lang_name: "Dutch", native: "Dutch" },
  { lang_code: "dz", lang_name: "Dzongkha", native: "Dzongkha" },
  { lang_code: "en", lang_name: "English", native: "English" },
  { lang_code: "eo", lang_name: "Esperanto", native: "Esperanto" },
  { lang_code: "et", lang_name: "Estonian", native: "Estonian" },
  { lang_code: "ee", lang_name: "Ewe", native: "Ewe" },
  { lang_code: "fo", lang_name: "Faroese", native: "Faroese" },
  { lang_code: "fj", lang_name: "Fijian", native: "Fijian" },
  { lang_code: "fi", lang_name: "Finnish", native: "Finnish" },
  { lang_code: "fr", lang_name: "French", native: "Français" },
  { lang_code: "ff", lang_name: "Fula, Fulah, Pulaar, Pular", native: "Fula, Fulah, Pulaar, Pular" },
  { lang_code: "gl", lang_name: "Galician", native: "Galician" },
  { lang_code: "gd", lang_name: "Gaelic (Scottish)", native: "Gaelic (Scottish)" },
  { lang_code: "gv", lang_name: "Gaelic (Manx)", native: "Gaelic (Manx)" },
  { lang_code: "ka", lang_name: "Georgian", native: "Georgian" },
  { lang_code: "de", lang_name: "German", native: "Deutsch" },
  { lang_code: "el", lang_name: "Greek", native: "Greek" },
  { lang_code: "kl", lang_name: "Greenlandic", native: "Greenlandic" },
  { lang_code: "gn", lang_name: "Guarani", native: "Guarani" },
  { lang_code: "gu", lang_name: "Gujarati", native: "Gujarati" },
  { lang_code: "ht", lang_name: "Haitian Creole", native: "Haitian Creole" },
  { lang_code: "ha", lang_name: "Hausa", native: "Hausa" },
  { lang_code: "he", lang_name: "Hebrew", native: "Hebrew" },
  { lang_code: "hz", lang_name: "Herero", native: "Herero" },
  { lang_code: "hi", lang_name: "Hindi", native: "Hindi" },
  { lang_code: "ho", lang_name: "Hiri Motu", native: "Hiri Motu" },
  { lang_code: "hu", lang_name: "Hungarian", native: "Hungarian" },
  { lang_code: "is", lang_name: "Icelandic", native: "Icelandic" },
  { lang_code: "io", lang_name: "Ido", native: "Ido" },
  { lang_code: "ig", lang_name: "Igbo", native: "Igbo" },
  { lang_code: "id", lang_name: "Indonesian", native: "Indonesian" },
  { lang_code: "in", lang_name: "Indonesian", native: "Indonesian" },
  { lang_code: "ia", lang_name: "Interlingua", native: "Interlingua" },
  { lang_code: "ie", lang_name: "Interlingue", native: "Interlingue" },
  { lang_code: "iu", lang_name: "Inuktitut", native: "Inuktitut" },
  { lang_code: "ik", lang_name: "Inupiak", native: "Inupiak" },
  { lang_code: "ga", lang_name: "Irish", native: "Irish" },
  { lang_code: "it", lang_name: "Italian", native: "Italiano" },
  { lang_code: "ja", lang_name: "Japanese", native: "日本語" },
  { lang_code: "jv", lang_name: "Javanese", native: "Javanese" },
  { lang_code: "kn", lang_name: "Kannada", native: "Kannada" },
  { lang_code: "kr", lang_name: "Kanuri", native: "Kanuri" },
  { lang_code: "ks", lang_name: "Kashmiri", native: "Kashmiri" },
  { lang_code: "kk", lang_name: "Kazakh", native: "Kazakh" },
  { lang_code: "km", lang_name: "Khmer", native: "Khmer" },
  { lang_code: "ki", lang_name: "Kikuyu", native: "Kikuyu" },
  { lang_code: "rw", lang_name: "Kinyarwanda (Rwanda)", native: "Kinyarwanda (Rwanda)" },
  { lang_code: "rn", lang_name: "Kirundi", native: "Kirundi" },
  { lang_code: "ky", lang_name: "Kyrgyz", native: "Kyrgyz" },
  { lang_code: "kv", lang_name: "Komi", native: "Komi" },
  { lang_code: "kg", lang_name: "Kongo", native: "Kongo" },
  { lang_code: "ko", lang_name: "Korean", native: "한국어" },
  { lang_code: "ku", lang_name: "Kurdish", native: "Kurdish" },
  { lang_code: "kj", lang_name: "Kwanyama", native: "Kwanyama" },
  { lang_code: "lo", lang_name: "Lao", native: "Lao" },
  { lang_code: "la", lang_name: "Latin", native: "Latin" },
  { lang_code: "lv", lang_name: "Latvian (Lettish)", native: "Latvian (Lettish)" },
  { lang_code: "li", lang_name: "Limburgish (Limburger)", native: "Limburgish (Limburger)" },
  { lang_code: "ln", lang_name: "Lingala", native: "Lingala" },
  { lang_code: "lt", lang_name: "Lithuanian", native: "Lithuanian" },
  { lang_code: "lu", lang_name: "Luga-Katanga", native: "Luga-Katanga" },
  { lang_code: "lg", lang_name: "Luganda, Ganda", native: "Luganda, Ganda" },
  { lang_code: "lb", lang_name: "Luxembourgish", native: "Luxembourgish" },
  { lang_code: "mk", lang_name: "Macedonian", native: "Macedonian" },
  { lang_code: "mg", lang_name: "Malagasy", native: "Malagasy" },
  { lang_code: "ms", lang_name: "Malay", native: "Malay" },
  { lang_code: "ml", lang_name: "Malayalam", native: "Malayalam" },
  { lang_code: "mt", lang_name: "Maltese", native: "Maltese" },
  { lang_code: "mi", lang_name: "Maori", native: "Maori" },
  { lang_code: "mr", lang_name: "Marathi", native: "Marathi" },
  { lang_code: "mh", lang_name: "Marshallese", native: "Marshallese" },
  { lang_code: "mo", lang_name: "Moldavian", native: "Moldavian" },
  { lang_code: "mn", lang_name: "Mongolian", native: "Mongolian" },
  { lang_code: "na", lang_name: "Nauru", native: "Nauru" },
  { lang_code: "nv", lang_name: "Navajo", native: "Navajo" },
  { lang_code: "ng", lang_name: "Ndonga", native: "Ndonga" },
  { lang_code: "nd", lang_name: "Northern Ndebele", native: "Northern Ndebele" },
  { lang_code: "ne", lang_name: "Nepali", native: "Nepali" },
  { lang_code: "no", lang_name: "Norwegian", native: "Norwegian" },
  { lang_code: "nb", lang_name: "Norwegian bokmål", native: "Norwegian bokmål" },
  { lang_code: "nn", lang_name: "Norwegian Nynorsk", native: "Norwegian Nynorsk" },
  { lang_code: "ii", lang_name: "Nuosu, Sichuan Yi", native: "Sichuan Yi, Nuosu" },
  { lang_code: "oc", lang_name: "Occitan", native: "Occitan" },
  { lang_code: "oj", lang_name: "Ojibwe", native: "Ojibwe" },
  { lang_code: "cu", lang_name: "Old Church Slavonic, Old Bulgarian", native: "Old Church Slavonic, Old Bulgarian" },
  { lang_code: "or", lang_name: "Oriya", native: "Oriya" },
  { lang_code: "om", lang_name: "Oromo (Afaan Oromo)", native: "Oromo (Afaan Oromo)" },
  { lang_code: "os", lang_name: "Ossetian", native: "Ossetian" },
  { lang_code: "pi", lang_name: "Pāli", native: "Pāli" },
  { lang_code: "ps", lang_name: "Pashto, Pushto", native: "Pashto, Pushto" },
  { lang_code: "fa", lang_name: "Persian (Farsi)", native: "Persian (Farsi)" },
  { lang_code: "pl", lang_name: "Polish", native: "Polish" },
  { lang_code: "pt", lang_name: "Portuguese", native: "Portuguese" },
  { lang_code: "pa", lang_name: "Punjabi (Eastern)", native: "Punjabi (Eastern)" },
  { lang_code: "qu", lang_name: "Quechua", native: "Quechua" },
  { lang_code: "rm", lang_name: "Romansh", native: "Romansh" },
  { lang_code: "ro", lang_name: "Romanian", native: "Romanian" },
  { lang_code: "ru", lang_name: "Russian", native: "Russian" },
  { lang_code: "se", lang_name: "Sami", native: "Sami" },
  { lang_code: "sm", lang_name: "Samoan", native: "Samoan" },
  { lang_code: "sg", lang_name: "Sango", native: "Sango" },
  { lang_code: "sa", lang_name: "Sanskrit", native: "Sanskrit" },
  { lang_code: "sr", lang_name: "Serbian", native: "Serbian" },
  { lang_code: "sh", lang_name: "Serbo-Croatian", native: "Serbo-Croatian" },
  { lang_code: "st", lang_name: "Sesotho", native: "Sesotho" },
  { lang_code: "tn", lang_name: "Setswana", native: "Setswana" },
  { lang_code: "sn", lang_name: "Shona", native: "Shona" },
  { lang_code: "sd", lang_name: "Sindhi", native: "Sindhi" },
  { lang_code: "si", lang_name: "Sinhalese", native: "Sinhalese" },
  { lang_code: "ss", lang_name: "Siswati, Swati", native: "Siswati, Swati" },
  { lang_code: "sk", lang_name: "Slovak", native: "Slovak" },
  { lang_code: "sl", lang_name: "Slovenian", native: "Slovenian" },
  { lang_code: "so", lang_name: "Somali", native: "Somali" },
  { lang_code: "nr", lang_name: "Southern Ndebele", native: "Southern Ndebele" },
  { lang_code: "es", lang_name: "Spanish", native: "Spanish" },
  { lang_code: "su", lang_name: "Sundanese", native: "Sundanese" },
  { lang_code: "sw", lang_name: "Swahili (Kiswahili)", native: "Swahili (Kiswahili)" },
  { lang_code: "sv", lang_name: "Swedish", native: "Swedish" },
  { lang_code: "tl", lang_name: "Tagalog", native: "Tagalog" },
  { lang_code: "ty", lang_name: "Tahitian", native: "Tahitian" },
  { lang_code: "tg", lang_name: "Tajik", native: "Tajik" },
  { lang_code: "ta", lang_name: "Tamil", native: "Tamil" },
  { lang_code: "tt", lang_name: "Tatar", native: "Tatar" },
  { lang_code: "te", lang_name: "Telugu", native: "Telugu" },
  { lang_code: "th", lang_name: "Thai", native: "Thai" },
  { lang_code: "bo", lang_name: "Tibetan", native: "Tibetan" },
  { lang_code: "ti", lang_name: "Tigrinya", native: "Tigrinya" },
  { lang_code: "to", lang_name: "Tonga", native: "Tonga" },
  { lang_code: "ts", lang_name: "Tsonga", native: "Tsonga" },
  { lang_code: "tr", lang_name: "Turkish", native: "Turkish" },
  { lang_code: "tk", lang_name: "Turkmen", native: "Turkmen" },
  { lang_code: "tw", lang_name: "Twi", native: "Twi" },
  { lang_code: "ug", lang_name: "Uyghur", native: "Uyghur" },
  { lang_code: "uk", lang_name: "Ukrainian", native: "Ukrainian" },
  { lang_code: "ur", lang_name: "Urdu", native: "Urdu" },
  { lang_code: "uz", lang_name: "Uzbek", native: "Uzbek" },
  { lang_code: "ve", lang_name: "Venda", native: "Venda" },
  { lang_code: "vi", lang_name: "Vietnamese", native: "Vietnamese" },
  { lang_code: "vo", lang_name: "Volapük", native: "Volapük" },
  { lang_code: "wa", lang_name: "Walloon", native: "Wallon" },
  { lang_code: "cy", lang_name: "Welsh", native: "Welsh" },
  { lang_code: "wo", lang_name: "Wolof", native: "Wolof" },
  { lang_code: "fy", lang_name: "Western Frisian", native: "Western Frisian" },
  { lang_code: "xh", lang_name: "Xhosa", native: "Xhosa" },
  { lang_code: "yi", lang_name: "Yiddish", native: "Yiddish" },
  { lang_code: "ji", lang_name: "Yiddish", native: "Yiddish" },
  { lang_code: "yo", lang_name: "Yoruba", native: "Yoruba" },
  { lang_code: "za", lang_name: "Zhuang, Chuang", native: "Zhuang, Chuang" },
  { lang_code: "zu", lang_name: "Zulu", native: "Zulu" },
];
