export const F_INSTAGRAM_POST = {
  uuid_36: {
    id: "uuid_36",
    label: "UUID 36",
    is_required: true,
    max_length: 36,
    placeholder: "ex. 123e4567-e89b-12d3-a456-426614174000",
  },
  instagram_post_url: {
    id: "instagram_post_url",
    label: "Instagram Post URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.instagram.com/p/1234567890/",
  },
  post_type: {
    id: "post_type",
    label: "Post Type",
    is_required: true,
    max_length: 20,
    placeholder: "ex. 'image', 'video', 'carousel', 'reel', 'story'",
  },
  media_count: {
    id: "media_count",
    label: "Media Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 1, 2, 3, ...",
    default_value: 1,
  },
  media_urls: {
    id: "media_urls",
    label: "Media URLs",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  og_title: {
    id: "og_title",
    label: "OG Title",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Title",
  },
  og_description: {
    id: "og_description",
    label: "OG Description",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Description",
    default_value: null,
  },
  og_image: {
    id: "og_image",
    label: "OG Image",
    is_required: false,
    max_length: 2048,
    placeholder: "ex. OG Image",
    default_value: null,
  },
  og_url: {
    id: "og_url",
    label: "OG URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG URL",
    default_value: null,
  },
  og_ios_url: {
    id: "og_ios_url",
    label: "OG iOS URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG iOS URL",
    default_value: null,
  },
  og_android_package: {
    id: "og_android_package",
    label: "OG Android Package",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Android Package",
    default_value: null,
  },
  og_android_url: {
    id: "og_android_url",
    label: "OG Android URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. OG Android URL",
    default_value: null,
  },
  info_country: {
    id: "info_country",
    label: "Info Country",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_city: {
    id: "info_city",
    label: "Info City",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_district: {
    id: "info_district",
    label: "Info District",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_neighborhood: {
    id: "info_neighborhood",
    label: "Info Neighborhood",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_landmark: {
    id: "info_landmark",
    label: "Info Landmark",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_category: {
    id: "info_category",
    label: "Info Category",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_name: {
    id: "info_name",
    label: "Info Name",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_special_tag: {
    id: "info_special_tag",
    label: "Info Special Tag",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_influencer: {
    id: "info_influencer",
    label: "Info Influencer",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_season: {
    id: "info_season",
    label: "Info Season",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_time_of_day: {
    id: "info_time_of_day",
    label: "Info Time of Day",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_activity_type: {
    id: "info_activity_type",
    label: "Info Activity Type",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  info_reservation_required: {
    id: "info_reservation_required",
    label: "Info Reservation Required",
    is_required: false,
    max_length: 10,
    placeholder: "ex. default value is null",
    default_value: null,
  },
  info_travel_tips: {
    id: "info_travel_tips",
    label: "Info Travel Tips",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  like_count: {
    id: "like_count",
    label: "Like Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  comment_count: {
    id: "comment_count",
    label: "Comment Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  view_count: {
    id: "view_count",
    label: "View Count",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 100",
    default_value: 0,
  },
  description: {
    id: "description",
    label: "Description",
    is_required: false,
    max_length: 2047,
    placeholder: "ex. Description",
    default_value: null,
  },
  tags: {
    id: "tags",
    label: "Tags",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT[]",
    default_value: null,
  },
  user_id: {
    id: "user_id",
    label: "User ID",
    is_required: false,
    max_length: 50,
    placeholder: "ex. User ID",
    default_value: null,
  },
  user_name: {
    id: "user_name",
    label: "User Name",
    is_required: false,
    max_length: 255,
    placeholder: "ex. User Name",
    default_value: null,
  },
  user_profile_url: {
    id: "user_profile_url",
    label: "User Profile URL",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. User Profile URL",
    default_value: null,
  },
  published_date: {
    id: "published_date",
    label: "Published Date",
    is_required: false,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
    default_value: null,
  },
  local_image_url: {
    id: "local_image_url",
    label: "Local Image URL",
    is_required: false,
    max_length: 511,
    placeholder: "ex. Local Image URL",
    default_value: null,
  },
  location_name: {
    id: "location_name",
    label: "Location Name",
    is_required: false,
    max_length: 255,
    placeholder: "ex. Location Name",
    default_value: null,
  },
  location_id: {
    id: "location_id",
    label: "Location ID",
    is_required: false,
    max_length: 100,
    placeholder: "ex. Location ID",
    default_value: null,
  },
  latitude: {
    id: "latitude",
    label: "Latitude",
    is_required: false,
    max_length: 20,
    placeholder: "ex. Latitude",
    default_value: null,
  },
  longitude: {
    id: "longitude",
    label: "Longitude",
    is_required: false,
    max_length: 20,
    placeholder: "ex. Longitude",
    default_value: null,
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
    default_value: null,
  },
  metadata_json: {
    id: "metadata_json",
    label: "Metadata JSON",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. JSON",
    default_value: null,
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "true",
  },
  is_deleted: {
    id: "is_deleted",
    label: "Is Deleted",
    is_required: false,
    max_length: 10,
    placeholder: "ex. true, false",
    default_value: "false",
  },
  deleted_at: {
    id: "deleted_at",
    label: "Deleted At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
    default_value: null,
  },
};
