export const F_PROCESSING_LOG_INSTAGRAM_POST = {
  id: {
    id: "id",
    label: "ID",
    is_required: true,
    max_length: 10,
    placeholder: "ex. 1, 2, 3, ...",
  },
  instagram_post_url: {
    id: "instagram_post_url",
    label: "Instagram Post URL",
    is_required: true,
    max_length: 1023,
    placeholder: "ex. https://www.instagram.com/p/1234567890/",
  },
  processing_status: {
    id: "name",
    label: "Processing Status",
    is_required: true,
    max_length: 20,
    placeholder: "ex. pending, processing, completed, failed",
    default_value: "pending",
  },
  index_name: {
    id: "index_name",
    label: "Pinecone Index Name",
    is_required: true,
    max_length: 255,
    placeholder: "PK ex. food_restaurants_index",
  },
  is_data_fetched: {
    id: "is_data_fetched",
    label: "Is Data Fetched",
    is_required: true,
    placeholder: "ex. false",
    default_value: false,
  },
  is_pinecone_processed: {
    id: "is_pinecone_processed",
    label: "Is Pinecone Processed",
    is_required: true,
    placeholder: "ex. false",
    default_value: false,
  },
  is_error_occurred: {
    id: "is_error_occurred",
    label: "Is Error Occurred",
    is_required: true,
    placeholder: "ex. false",
    default_value: false,
  },
  error_message: {
    id: "error_message",
    label: "Error Message",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. TEXT",
    default_value: null,
  },
  processing_started: {
    id: "processing_started",
    label: "Processing Started",
    is_required: false,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  processing_completed: {
    id: "processing_completed",
    label: "Processing Completed",
    is_required: false,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  retry_count: {
    id: "retry_count",
    label: "Retry Count",
    is_required: true,
    placeholder: "ex. 0",
    default_value: 0,
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: true,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  last_processed_at: {
    id: "last_processed_at",
    label: "Last Processed At",
    is_required: false,
    max_length: 100,
    placeholder: "ex. TIMESTAMP",
  },
  source: {
    id: "source",
    label: "Source",
    is_required: true,
    max_length: 50,
    placeholder: "ex. youtube",
  },
  priority: {
    id: "priority",
    label: "Priority",
    is_required: true,
    max_length: 50,
    placeholder: "ex. 1, 2, 3, ...",
    default_value: 5,
  },
  assigned_worker: {
    id: "assigned_worker",
    label: "Assigned Worker",
    is_required: false,
    max_length: 100,
    placeholder: "ex. worker_1, worker_2, etc.",
  },
};
