export const F_LANDMARK = {
  id: {
    id: "id",
    label: "ID",
    is_required: true,
    max_length: 10,
    placeholder: "Primary Key ex. 1234567890",
  },
  country_code: {
    id: "country_code",
    label: "Country Code",
    is_required: false,
    max_length: 2,
    placeholder: "ex. KR",
  },
  city_code: {
    id: "city_code",
    label: "City Code",
    is_required: false,
    max_length: 96,
    placeholder: "Primary Key ex. seoul, jeju, bangkok, etc.",
  },
  name_en: {
    id: "name_en",
    label: "Landmark Name (en)",
    is_required: true,
    max_length: 100,
    placeholder: "ex. Seoul",
  },
  name_native: {
    id: "name_native",
    label: "Landmark Name (native)",
    is_required: false,
    max_length: 100,
    placeholder: "ex. 서울",
  },
  name_ko: {
    id: "name_ko",
    label: "Landmark Name (ko)",
    is_required: false,
    max_length: 100,
    placeholder: "ex. 서울",
  },
  order_num: {
    id: "order_num",
    label: "Order(Number)",
    is_required: true,
    placeholder: "ex. 1, 2, 3, ...",
    default_value: 0,
  },
  description_en: {
    id: "description_en",
    label: "Description (en)",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. 서울은 대한민국의 수도입니다.",
  },
  description_native: {
    id: "description_native",
    label: "Description (native)",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. 서울은 대한민국의 수도입니다.",
  },
  google_place_id: {
    id: "google_place_id",
    label: "Google Place ID",
    is_required: false,
    max_length: 63,
    placeholder: "ex. ChIJN1t_t3udTERG7k59uZwC8g",
  },
  youtube_ch_id: {
    id: "youtube_ch_id",
    label: "Youtube Channel ID",
    is_required: false,
    max_length: 48,
    placeholder: "ex. UCU-9-kyTW8ZkZNDHQJ6FgpwQ",
  },
  instagram_id: {
    id: "instagram_id",
    label: "Instagram ID",
    is_required: false,
    max_length: 48,
    placeholder: "ex. seoul",
  },
  latitude: {
    id: "latitude",
    label: "Latitude",
    is_required: false,
    placeholder: "37.532600 numeric(10, 8)",
  },
  longitude: {
    id: "longitude",
    label: "Longitude",
    is_required: false,
    placeholder: "127.024612 numeric(11, 8)",
  },
  location: {
    id: "location",
    label: "Location",
    is_required: false,
    max_length: 255,
    placeholder: "ex. Location",
  },
  radius_m: {
    id: "radius_m",
    label: "City Radius",
    is_required: false,
    placeholder: "1000 (unit: meters)",
  },
  address_en: {
    id: "address_en",
    label: "Address (en)",
    is_required: true,
    max_length: 255,
    placeholder: "ex. Jung-gu, Seoul, Korea",
  },
  address_native: {
    id: "address_native",
    label: "Address Native",
    is_required: true,
    max_length: 255,
    placeholder: "ex. 서울특별시 중구 세종대로 110",
  },
  google_map_url: {
    id: "google_map_url",
    label: "Google Map URL",
    is_required: true,
    max_length: 255,
    placeholder: "ex. https://www.google.com/maps/place/?cid=1234567890",
  },
  naver_map_url: {
    id: "naver_map_url",
    label: "Naver Map URL",
    is_required: false,
    max_length: 255,
  },
  created_at: {
    id: "created_at",
    label: "Created At",
    is_required: true,
    placeholder: "ex. TIMESTAMP",
  },
  created_by: {
    id: "created_by",
    label: "Created By",
    is_required: false,
    max_length: 511,
    placeholder: "ex. aid",
  },
  updated_at: {
    id: "updated_at",
    label: "Updated At",
    is_required: false,
    placeholder: "ex. TIMESTAMP",
  },
  is_active: {
    id: "is_active",
    label: "Is Active",
    is_required: true,
    default_value: false,
  },
  deactivated_at: {
    id: "deactivated_at",
    label: "Deactivated At",
    is_required: false,
    placeholder: "ex. aid",
  },
  deactivated_by: {
    id: "deactivated_by",
    label: "Deactivated By",
    is_required: false,
    max_length: 511,
    placeholder: "ex. aid",
  },
  is_display: {
    id: "is_display",
    label: "Is Display",
    is_required: true,
    default_value: true,
  },
  thumbnail_main_1: {
    id: "thumbnail_main_1",
    label: "Thumbnail Main 1",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_main_2: {
    id: "thumbnail_main_2",
    label: "Thumbnail Main 2",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_main_3: {
    id: "thumbnail_main_3",
    label: "Thumbnail Main 3",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_main_4: {
    id: "thumbnail_main_4",
    label: "Thumbnail Main 4",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_main_5: {
    id: "thumbnail_main_5",
    label: "Thumbnail Main 5",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_1: {
    id: "thumbnail_1",
    label: "Thumbnail 1",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_2: {
    id: "thumbnail_2",
    label: "Thumbnail 2",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_3: {
    id: "thumbnail_3",
    label: "Thumbnail 3",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_4: {
    id: "thumbnail_4",
    label: "Thumbnail 4",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_5: {
    id: "thumbnail_5",
    label: "Thumbnail 5",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_vertical_1: {
    id: "thumbnail_vertical_1",
    label: "Thumbnail Vertical 1",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_vertical_2: {
    id: "thumbnail_vertical_2",
    label: "Thumbnail Vertical 2",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_vertical_3: {
    id: "thumbnail_vertical_3",
    label: "Thumbnail Vertical 3",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_vertical_4: {
    id: "thumbnail_vertical_4",
    label: "Thumbnail Vertical 4",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
  thumbnail_vertical_5: {
    id: "thumbnail_vertical_5",
    label: "Thumbnail Vertical 5",
    is_required: false,
    max_length: 1023,
    placeholder: "ex. https://www.seoul.go.kr/images/city/thumbnail.jpg",
  },
};
